# Cilium v1.20.1
# Kubernetes v1.36.4 / kube-proxy-free cluster

kubeProxyReplacement: true

k8sServiceHost: 192.168.184.235
k8sServicePort: "6443"

routingMode: tunnel
tunnelProtocol: vxlan

bpf:
  masquerade: true

egressGateway:
  enabled: true

ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.200.0.0/16
    clusterPoolIPv4MaskSize: 24
